In [1]:
import pandas as pd
import numpy as np

In [2]:
df_All_merchant_NS = pd.read_csv(r"C:\Users\kiano.keynejad\Documents\1st Oct May\All_Merchant_profile_May.csv")
df_All_merchant_NS.head()

,Merchant ID,Company Name,MCC code,Business Industry,Price Model,MSF CC %,MSF DC $,Shipping State/Province,Shipping Zip,Default Brand
0,SP7020000002629,Zetland Hotel At Green Square,5813,Bars/Taverns/Night Clubs,SmartCharge,1.65%,0.30,New South Wales,2017.0,Smartpay
1,SP7040000000601,Portsmith Quality Meats,5422,"Butcher, Frozen Meats, Seafood",SmartCharge,1.65%,0.30,Queensland,4870.0,Smartpay
2,SP7030000005012,Anatolia Gozleme Kitchen,5812,"Eating Places, Restaurants",SmartCharge,1.2%,0.30,VIC,3181.0,Smartpay
3,SP7040000004162,Aussizz Migration And Education acc 2,8111,"Attorneys, Legal Services",SmartCharge,1.65%,0.30,QLD,4000.0,Smartpay
4,SP7030000004317,Freechoice Werribee,5993,Tobacco Shops,Simple rate,0.99%,0.22,Victoria,3030.0,Smartpay

In [3]:
df_profit_May = pd.read_csv(r"C:\Users\kiano.keynejad\Documents\1st Oct May\Profit Analysis - May 26.csv")
df_profit_May.head()

,Merchant ID,Trading Name,Mcc,Count of Transacting Terminal IDs,Number of Transactions,Value of Transactions,Average of Transactions,COGS,MSF Margin
0,SA7020010044294,ZA Tobacconist Campbelltown,5993 - Tobacco Shops,2.0,19516.0,"$1,017,225.78",$52.12,"$2,706.82","$9,987.37"
1,SA7040010000920,The Meat Hub Gold Coast,"5422 - Butcher, Frozen Meats, Seafood",3.0,13247.0,"$1,062,839.08",$80.23,"$3,409.21","$9,469.64"
2,SA7030010004444,CBD Movers,"4214 - Freight Carriers, Trucking and Storage ...",59.0,1217.0,"$650,260.53",$534.31,"$1,596.75","$7,413.75"
3,SP7020000018176,The Fresh Fruit Team,5499 - Misc. Food Stores - Convenience & Speci...,7.0,27511.0,"$719,613.45",$26.16,"$5,706.56","$4,554.59"
4,SA7020010013531,Umina Convenience Store,5993 - Tobacco Shops,2.0,7219.0,"$369,434.60",$51.18,$965.41,"$4,453.74"

In [4]:
df_profit_May['Merchant ID'].duplicated().sum()

np.int64(0)

In [5]:
# inner merge to only keep merchant with open-active account
df_merged = pd.merge( df_All_merchant_NS, df_profit_May, how='inner', on='Merchant ID')

In [6]:
df_merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 14652 entries, 0 to 14651
Data columns (total 18 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Merchant ID                        14652 non-null  str
 1   Company Name                       14652 non-null  str
 2   MCC code                           14652 non-null  int64
 3   Business Industry                  14652 non-null  str
 4   Price Model                        14652 non-null  str
 5   MSF CC %                           14448 non-null  str
 6   MSF DC $                           14453 non-null  float64
 7   Shipping State/Province            14650 non-null  str
 8   Shipping Zip                       14651 non-null  float64
 9   Default Brand                      14652 non-null  str
 10  Trading Name                       14347 non-null  str
 11  Mcc                                14347 non-null  str
 12  Count of Transacting Terminal IDs  14077 non-null  float64
 13  Number of Transactions             14077 non-null  float64
 14  Value of Transactions              14077 non-null  str
 15  Average of Transactions            14652 non-null  str
 16  COGS                               14077 non-null  str
 17  MSF Margin                         14652 non-null  str
dtypes: float64(4), int64(1), str(13)
memory usage: 2.0 MB

In [7]:
df_merged.isnull().sum()

Merchant ID                            0
Company Name                           0
MCC code                               0
Business Industry                      0
Price Model                            0
MSF CC %                             204
MSF DC $                             199
Shipping State/Province                2
Shipping Zip                           1
Default Brand                          0
Trading Name                         305
Mcc                                  305
Count of Transacting Terminal IDs    575
Number of Transactions               575
Value of Transactions                575
Average of Transactions                0
COGS                                 575
MSF Margin                             0
dtype: int64

In [8]:
df_merged['Merchant ID'].duplicated().sum()

np.int64(0)

In [9]:
print(df_merged.columns.tolist())

['Merchant ID', 'Company Name', 'MCC code', 'Business Industry', 'Price Model', 'MSF CC %', 'MSF DC $', 'Shipping State/Province', 'Shipping Zip', 'Default Brand', 'Trading Name', 'Mcc', 'Count of Transacting Terminal IDs', 'Number of Transactions', 'Value of Transactions', 'Average of Transactions', 'COGS', 'MSF Margin']

In [10]:
def cleaned_merged(series):
    return pd.to_numeric(series
        .astype('string')
        .str.strip()
        .str.replace('$', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.replace('%', '', regex=False),
        errors='coerce'
    ).fillna(0)
df_merged['MSF DC $'] = cleaned_merged(df_merged['MSF DC $'])
df_merged['MSF CC %'] = cleaned_merged(df_merged['MSF CC %'])
df_merged['Number of Transactions'] = cleaned_merged(df_merged['Number of Transactions'])
df_merged['Value of Transactions'] = cleaned_merged(df_merged['Value of Transactions'])
df_merged['Average of Transactions'] = cleaned_merged(df_merged['Average of Transactions'])
df_merged['COGS'] = cleaned_merged(df_merged['COGS'])
df_merged['MSF Margin'] = cleaned_merged(df_merged['MSF Margin'])

In [11]:
df_merged = df_merged[df_merged['MSF CC %'] > 0 ]
df_merged.info()

<class 'pandas.DataFrame'>
Index: 14277 entries, 0 to 14651
Data columns (total 18 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Merchant ID                        14277 non-null  str
 1   Company Name                       14277 non-null  str
 2   MCC code                           14277 non-null  int64
 3   Business Industry                  14277 non-null  str
 4   Price Model                        14277 non-null  str
 5   MSF CC %                           14277 non-null  Float64
 6   MSF DC $                           14277 non-null  Float64
 7   Shipping State/Province            14275 non-null  str
 8   Shipping Zip                       14276 non-null  float64
 9   Default Brand                      14277 non-null  str
 10  Trading Name                       13972 non-null  str
 11  Mcc                                13972 non-null  str
 12  Count of Transacting Terminal IDs  13702 non-null  float64
 13  Number of Transactions             14277 non-null  Float64
 14  Value of Transactions              14277 non-null  Float64
 15  Average of Transactions            14277 non-null  Float64
 16  COGS                               14277 non-null  Float64
 17  MSF Margin                         14277 non-null  Float64
dtypes: Float64(7), float64(2), int64(1), str(8)
memory usage: 2.2 MB

In [12]:
bins = [0, 0.9, 1.0, 1.2, 1.4, 1.65, float('inf')]
labels = ['0.0-0.9', '0.9-1.0', '1.0-1.2', '1.2-1.4', '1.4-1.65', '1.65+']
df_merged['Rate segment'] = pd.cut(
    df_merged['MSF CC %'],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [13]:
df_merged.head()

,Merchant ID,Company Name,MCC code,Business Industry,Price Model,MSF CC %,MSF DC $,Shipping State/Province,Shipping Zip,Default Brand,Trading Name,Mcc,Count of Transacting Terminal IDs,Number of Transactions,Value of Transactions,Average of Transactions,COGS,MSF Margin,Rate segment
0,SP7030000005012,Anatolia Gozleme Kitchen,5812,"Eating Places, Restaurants",SmartCharge,1.2,0.3,VIC,3181.0,Smartpay,Anatolia Gozleme Kitchen,"5812 - Eating Places, Restaurants",2.0,8187.0,134626.85,16.44,1142.81,313.96,1.0-1.2
1,SP7040000004162,Aussizz Migration And Education acc 2,8111,"Attorneys, Legal Services",SmartCharge,1.65,0.3,QLD,4000.0,Smartpay,Aussizz Migration And Education acc 2,"8111 - Attorneys, Legal Services",1.0,17.0,6719.13,395.24,2.38,132.57,1.4-1.65
2,SP7030000004317,Freechoice Werribee,5993,Tobacco Shops,Simple rate,0.99,0.22,Victoria,3030.0,Smartpay,NaN,NaN,NaN,0.0,0.0,0.0,0.0,100.0,0.9-1.0
3,SP7030000005066,Bella and Home Decor,5712,"Furniture, Home Furnishings, and Equipment Sto...",Simple rate,1.05,0.24,VIC,3803.0,Smartpay,Bella and Home Decor,"5712 - Furniture, Home Furnishings, and Equipm...",2.0,88.0,23867.9,271.23,95.31,444.76,1.0-1.2
4,SP7030000004158,Afghan Kebab Campbellfield,5812,"Eating Places, Restaurants",SmartCharge,1.1,0.25,VIC,3061.0,Smartpay,Afghan Kebab Campbellfield,"5812 - Eating Places, Restaurants",1.0,2378.0,121336.02,51.02,398.95,798.04,1.0-1.2

In [14]:
bins = [0, 50000, 100000, float('inf')]
labels = ['0-50K', '50K-100K', '100K+']
df_merged ['Tiers'] = pd.cut(
    df_merged['Value of Transactions'],
    bins=bins,
    labels=labels,
    include_lowest=True,
    right=False
)
df_merged = df_merged[df_merged['Value of Transactions'] > 0]

In [15]:
df_merged = df_merged.rename(
    columns={
        'Shipping State/Province' : 'State',
        'Shipping Zip' : 'PostCode'
    }
)
df_merged = df_merged.drop(
    columns=[
        'Trading Name', 'Mcc',
    ]
)

In [16]:
df_merged['State'].unique()

<StringArray>
[                         'VIC',                          'QLD',
                           'SA',                   'Queensland',
              'New South Wales',                     'Victoria',
                          'ACT',                          'NSW',
                           'NT',                           'WA',
                          'TAS',            'Western Australia',
              'South Australia', 'Australian Capital Territory',
                            nan,                     'Tasmania',
           'Northern Territory']
Length: 17, dtype: str

In [17]:
state_mapping = {
    'New South Wales': 'NSW',
    'Victoria': 'VIC',
    'Queensland': 'QLD',
    'South Australia': 'SA',
    'Western Australia': 'WA',
    'Tasmania': 'TAS',
    'Northern Territory': 'NT',
    'Australian Capital Territory': 'ACT'
}

df_merged['State'] = df_merged['State'].replace(state_mapping)

In [18]:
df_debit_analysis = pd.read_csv(r"C:\Users\kiano.keynejad\Documents\1st Oct May\Monthly Analysis Debit_Credit_May.csv")

In [19]:
df_debit_analysis.head()

,Merchant ID,% Eftpos (non-Tap),% Eftpos Tap,% Eftpos Total,% Debit,% Credit,% International,% Total Tap
0,SA7020010044294,0.68%,67.12%,67.80%,29.50%,2.50%,0.20%,99.32%
1,SA7040010000920,3.20%,53.00%,56.20%,29.80%,13.10%,0.80%,96.70%
2,SA7030010004444,7.92%,45.28%,53.20%,33.10%,13.10%,0.60%,92.08%
3,SP7020000018176,0.77%,47.23%,48.00%,38.70%,13.10%,0.30%,99.33%
4,SA7020010013531,1.33%,68.07%,69.40%,27.00%,3.30%,0.30%,98.67%

In [20]:
df_merged = pd.merge(df_merged, df_debit_analysis, how='inner', on='Merchant ID')

In [21]:
df_merged.head()

,Merchant ID,Company Name,MCC code,Business Industry,Price Model,MSF CC %,MSF DC $,State,PostCode,Default Brand,...,MSF Margin,Rate segment,Tiers,% Eftpos (non-Tap),% Eftpos Tap,% Eftpos Total,% Debit,% Credit,% International,% Total Tap
0,SP7030000005012,Anatolia Gozleme Kitchen,5812,"Eating Places, Restaurants",SmartCharge,1.2,0.3,VIC,3181.0,Smartpay,...,313.96,1.0-1.2,100K+,0.15%,39.15%,39.30%,39.10%,19.40%,2.10%,99.75%
1,SP7040000004162,Aussizz Migration And Education acc 2,8111,"Attorneys, Legal Services",SmartCharge,1.65,0.3,QLD,4000.0,Smartpay,...,132.57,1.4-1.65,0-50K,0.00%,96.70%,96.70%,3.30%,0.00%,0.00%,100.00%
2,SP7030000005066,Bella and Home Decor,5712,"Furniture, Home Furnishings, and Equipment Sto...",Simple rate,1.05,0.24,VIC,3803.0,Smartpay,...,444.76,1.0-1.2,0-50K,3.90%,2.60%,6.50%,70.50%,23.00%,0.00%,96.10%
3,SP7030000004158,Afghan Kebab Campbellfield,5812,"Eating Places, Restaurants",SmartCharge,1.1,0.25,VIC,3061.0,Smartpay,...,798.04,1.0-1.2,100K+,0.45%,62.55%,63.00%,28.50%,7.90%,0.60%,99.55%
4,SP7030000002212,Byblos Market,5499,Misc. Food Stores - Convenience & Specialty Ma...,SmartCharge,1.65,0.3,VIC,3023.0,Smartpay,...,127.45,1.4-1.65,0-50K,0.00%,76.00%,76.00%,22.00%,2.00%,0.00%,100.00%

In [22]:
df_merged['% Eftpos (non-Tap)'] = cleaned_merged(df_merged['% Eftpos (non-Tap)'])
df_merged['% Eftpos Tap'] = cleaned_merged(df_merged['% Eftpos Tap'])
df_merged['% Eftpos Total'] = cleaned_merged(df_merged['% Eftpos Total'])
df_merged['% Debit'] = cleaned_merged(df_merged['% Debit'])
df_merged['% Credit'] = cleaned_merged(df_merged['% Credit'])
df_merged['% International'] = cleaned_merged(df_merged['% International'])
df_merged['% Total Tap'] = cleaned_merged(df_merged['% Total Tap'])

In [23]:
df_merged.to_csv('df_merged_May.csv', index=False)

In [24]:
# Industry Analysis
df_industry = (
    df_merged.groupby('Business Industry')
    .agg(
        total_merchants=('Merchant ID', 'count'),
        total_ttv=('Value of Transactions', 'sum'),
        msf = ('COGS', 'sum'),
        total_MSF_margin=('MSF Margin', 'sum'),
        Average_of_Transactions=('Average of Transactions', 'mean'),
        Average_Eftpos_NonTap_transactions=('% Eftpos (non-Tap)', 'mean'),
        Average_Eftpos_tap_transactions=('% Eftpos Tap', 'mean'),
        Average_Eftpos_transactions=('% Eftpos Total', 'mean'),
        Average_Debit_transactions=('% Debit', 'mean'),
        Average_Credit_transactions=('% Credit', 'mean'),
        Average_International_transactions=('% International', 'mean'),
            Average_Total_tap_transactions=('% Total Tap', 'mean'),
        smartcharge_merchants=(
            'Price Model',
            lambda x: (x == 'SmartCharge').sum()
        ),
        SFR_merchants=(
            'Price Model',
            lambda x: (x == 'Simple rate').sum()
        )
    )
    .reset_index()
)

In [25]:
 # Value must be sorted based on ttv otherwise cumulative ttv will be wrong
df_industry = df_industry.sort_values(
    by='total_ttv',
    ascending=False
)
# calculate cumulative TTV %
df_industry['ttv_cum_pct'] = (
    df_industry['total_ttv'].cumsum()
    / df_industry['total_ttv'].sum()
)

# calculate TTV %
df_industry['ttv_pct'] = (
    df_industry['total_ttv']
    / df_industry['total_ttv'].sum()
)

# cumulative MSF margin %
df_industry['MSF_margin_cum_pct'] = (
    df_industry['total_MSF_margin'].cumsum()
    / df_industry['total_MSF_margin'].sum()
)

# MSF margin %
df_industry['MSF_margin_pct'] = (
    df_industry['total_MSF_margin']
    / df_industry['total_MSF_margin'].sum()
)

# cumulative Smartcharge %
df_industry['smartcharge_cum_pct'] = (
   df_industry['smartcharge_merchants'].cumsum()
   / df_industry['smartcharge_merchants'].sum()
)

# Smartcharge %
df_industry['smartcharge_pct'] = (
   df_industry['smartcharge_merchants']
   / df_industry['smartcharge_merchants'].sum()
)


# cumulative SFR %
df_industry['SFR_cum_pct'] = (
  df_industry['SFR_merchants'].cumsum()
      / df_industry['SFR_merchants'].sum()
)

# SFR %
df_industry['SFR_pct'] = (
  df_industry['SFR_merchants']
      / df_industry['SFR_merchants'].sum()
)

In [26]:
df_industry.head()

,Business Industry,total_merchants,total_ttv,msf,total_MSF_margin,Average_of_Transactions,Average_Eftpos_NonTap_transactions,Average_Eftpos_tap_transactions,Average_Eftpos_transactions,Average_Debit_transactions,...,smartcharge_merchants,SFR_merchants,ttv_cum_pct,ttv_pct,MSF_margin_cum_pct,MSF_margin_pct,smartcharge_cum_pct,smartcharge_pct,SFR_cum_pct,SFR_pct
77,"Eating Places, Restaurants",2252,112547658.41,675146.55,779293.89,37.526967,1.136665,47.570528,48.707149,37.977798,...,2123,129,0.193537,0.193537,0.195814,0.195814,0.175818,0.175818,0.103865,0.103865
172,Repairs - Automotive Service Shops,1637,70661155.54,183904.94,414098.79,596.99212,20.327208,31.933696,52.26066,31.106475,...,1514,123,0.315046,0.121509,0.299865,0.104051,0.301201,0.125383,0.202899,0.099034
175,"Salons - Hair, Nails, Beauty (No Memberships)",2265,60866209.8,209606.76,591125.01,127.862013,6.185325,40.8503,47.035453,38.245784,...,2194,71,0.419711,0.104665,0.448397,0.148532,0.482899,0.181698,0.260064,0.057166
86,Fast Food Restaurant,929,36551113.32,239892.34,249651.5,25.881163,0.966405,52.20282,53.169214,36.149085,...,896,33,0.482564,0.062853,0.511127,0.06273,0.557101,0.074203,0.286634,0.026570
190,Tobacco Shops,383,35555991.55,160586.15,197375.43,43.761749,1.461253,43.143708,44.604961,47.943342,...,251,132,0.543706,0.061142,0.560722,0.049595,0.577888,0.020787,0.392915,0.106280

In [27]:
df_industry.to_csv('df_industry_May.csv', index=False)

In [28]:
# 1. Total TTV per industry
industry_ttv = (
    df_merged.groupby('Business Industry')['Value of Transactions']
    .sum()
    .sort_values(ascending=False)
)

# 2. Top 15 industries
top15_ttv = industry_ttv.head(15)

# 3. Total TTV overall
total_ttv = industry_ttv.sum()

# 4. Percentage contribution of top 15
top15_percentage = ((top15_ttv.sum() / total_ttv)*100).round(0)

print(top15_percentage)

82.0

In [29]:
result = pd.DataFrame({
    'Top 15 Industries TTV %': [(top15_ttv.sum() / total_ttv)],
    'Top 15 Industries TTV': [top15_ttv.sum()],
    'Total TTV': [total_ttv]
})
result.head()

   Top 15 Industries TTV %  Top 15 Industries TTV     Total TTV
0                 0.821986           4.780105e+08  5.815312e+08

In [30]:
print(df_industry.columns.tolist())

['Business Industry', 'total_merchants', 'total_ttv', 'msf', 'total_MSF_margin', 'Average_of_Transactions', 'Average_Eftpos_NonTap_transactions', 'Average_Eftpos_tap_transactions', 'Average_Eftpos_transactions', 'Average_Debit_transactions', 'Average_Credit_transactions', 'Average_International_transactions', 'Average_Total_tap_transactions', 'smartcharge_merchants', 'SFR_merchants', 'ttv_cum_pct', 'ttv_pct', 'MSF_margin_cum_pct', 'MSF_margin_pct', 'smartcharge_cum_pct', 'smartcharge_pct', 'SFR_cum_pct', 'SFR_pct']

In [31]:
print(df_merged.columns.tolist())

['Merchant ID', 'Company Name', 'MCC code', 'Business Industry', 'Price Model', 'MSF CC %', 'MSF DC $', 'State', 'PostCode', 'Default Brand', 'Count of Transacting Terminal IDs', 'Number of Transactions', 'Value of Transactions', 'Average of Transactions', 'COGS', 'MSF Margin', 'Rate segment', 'Tiers', '% Eftpos (non-Tap)', '% Eftpos Tap', '% Eftpos Total', '% Debit', '% Credit', '% International', '% Total Tap']